// Generated by analysis/analyze.py from the song and its lyric sheet. Placeholder until the first run.
const SONG = { duration: PROJECT.duration, bpm: PROJECT.bpm, beat: 60 / PROJECT.bpm, offset: PROJECT.offset || 0 };
const SECTIONS = [];
const LYRICS = [];
const barAt = t => (t - SONG.offset) / (4 * SONG.beat);
const timeOfBar = b => SONG.offset + b * 4 * SONG.beat;
